[mypy]
python_version = 3.10
packages = ["basyx_client"]
ignore_missing_imports = true

# If you want stricter type checking, uncomment these:
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
# check_untyped_defs = true
# disallow_untyped_decorators = true

# Exclude generated code
exclude = (?x)(
    python-client-generated/.*
    )

# Per-module settings for external libraries
[mypy-requests.*]
ignore_missing_imports = True

[mypy-basyx.*]
ignore_missing_imports = True