[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basyx-python-client-sdk"
version = "0.0.1"
description = "Connects to and interacts with AAS-Repositories"
readme = "README.md"
authors = [{ name = "Jannis Jung", email = "jannis.jung@iese.fraunhofer.de" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha"
]
keywords = ["eclipse", "basyx", "client", "sdk"]
dependencies = [
    "basyx-python-sdk==2.0.0",
    "requests>=2.32.5",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest", "mypy"]
test = ["flask>=3.1.3"]

[project.urls]
Homepage = "https://github.com/eclipse-basyx/basyx-python-sdk"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.15.5",
]
