[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basyx-python-client-sdk"
version = "0.0.1"
description = "Connects to and interacts with AAS-Repositories"
readme = "README.md"
authors = [{ name = "Jannis Jung", email = "jannis.jung@iese.fraunhofer.de" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha"
]
keywords = ["eclipse", "basyx", "client", "sdk"]
dependencies = [
    "basyx-python-sdk==2.0.0",
    "certifi==2026.2.25",
    "charset-normalizer==3.4.4",
    "idna==3.11",
    "lxml==6.0.2",
    "pyecma376-2==1.0.2",
    "python-dateutil==2.9.0.post0",
    "requests==2.32.5",
    "six==1.17.0",
    "urllib3==2.6.3",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/eclipse-basyx/basyx-python-sdk"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
